### ISSUE TITLE
Homepage Configurable Components

### ISSUE THREAD

**Issue by scrock1987** [JKTOpen/destiny#102]
The homepage should have certain Configurable components. Following are the identified components as of yet:
  - [x]  Homepage Slider
  - [x]  Category Based Product listing
    - [x] Name/Number of Categories to be displayed
    - [x] Number of products per Category
    - [x] Slider at categories
  - [x]  Promotional Offers Section

- [ ] These 3 must be configurable. Create admin interface for them.
  - [x] Admin UI for Category Slider
  - [x] Admin UI for Promotional offers

**Comment by plannifnminus1fails** [comment]
### Sample records in config collection: ###

{
"name": "cat_slider",
"value": "{
 products_quantity: 4,
 Categories: {
  "hjkhkj76bjkhjkh",
  "hkgaoakghgj78ab"
  }
 }"
}


{
"name": "offer_zone",
"value": "{
 offer_quantity: 6,
 offers: {
  offer1:{'title':'abc', 'img':'/image1.jpg', link:'/url/abc', html:'?????'},
  .
  .
  .
  offer6:{'title':'abc', 'img':'/image1.jpg', link:'/url/abc', html:'????'}
  
  }
 }"
}

**Comment by scrock1987** [comment]
Record to be present in config for category slider
{
    "categoryList": [
        {
            "_id": "54634e05a92d436556ae189a",
            "name": "Accessories",
            "description": "all types of accessories"
        },
        {
            "_id": "54634e58a92d436556ae189b",
            "name": "Carpets",
            "description": "all types of accessories"
        }
    ],
    "productsPerCategory": 3
}

**Comment by plannifnminus1fails** [comment]
Now i have changed config schema. we have these records;
```
{
  "name": "offer_zone",
  "value": {
    "offer_quantity": 2,
    "offers": {
      "offer1": {
        "title": "abc",
        "img": "image1.jpg",
        "link": "\/url\/abc",
        "html": "?????"
      },
      "offer6": {
        "title": "abc",
        "img": "image1.jpg",
        "link": "\/url\/abc",
        "html": "????"
      }
    }
  }
}
```

```
{
  "name": "cat_slider",
  "value": {
    "products_quantity": 3,
    "categories": [
      "54635342fd252e1cfff91d89",
      "54634e75a92d436556ae189c"
    ]
  }
}
```

**Comment by ghost** [comment]
Slider at categories is done.
